# Generated by Django 6.0.7 on 2026-08-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_enrollment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="user",
            new_name="student",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
