# Generated by Django 6.0.7 on 2026-08-04 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_options_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
    ]
